In [37]:
#연관규칙 분석 실습

In [38]:
# Machine Learning Extended 패키지 설치
!pip install mlxtend

Requirement already satisfied: mlxtend in c:\users\dbwls\anaconda3\lib\site-packages (0.23.3)
Requirement already satisfied: scipy>=1.2.1 in c:\users\dbwls\anaconda3\lib\site-packages (from mlxtend) (1.13.1)
Requirement already satisfied: numpy>=1.16.2 in c:\users\dbwls\anaconda3\lib\site-packages (from mlxtend) (1.26.4)
Requirement already satisfied: pandas>=0.24.2 in c:\users\dbwls\anaconda3\lib\site-packages (from mlxtend) (2.2.2)
Requirement already satisfied: scikit-learn>=1.3.1 in c:\users\dbwls\anaconda3\lib\site-packages (from mlxtend) (1.4.2)
Requirement already satisfied: matplotlib>=3.0.0 in c:\users\dbwls\anaconda3\lib\site-packages (from mlxtend) (3.8.4)
Requirement already satisfied: joblib>=0.13.2 in c:\users\dbwls\anaconda3\lib\site-packages (from mlxtend) (1.4.2)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\dbwls\anaconda3\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (1.2.0)
Requirement already satisfied: cycler>=0.10 in c:\users\dbwls\anaconda3\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\dbwls\anaconda3\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (4.51.0)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\dbwls\anaconda3\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (1.4.4)
Requirement already satisfied: packaging>=20.0 in c:\users\dbwls\anaconda3\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (23.2)
Requirement already satisfied: pillow>=8 in c:\users\dbwls\anaconda3\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (10.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\dbwls\anaconda3\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (3.0.9)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\dbwls\anaconda3\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\dbwls\anaconda3\lib\site-packages (from pandas>=0.24.2->mlxtend) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\dbwls\anaconda3\lib\site-packages (from pandas>=0.24.2->mlxtend) (2023.3)
Requirement already satisfied: threadpoolctl>=2.0.0 in c:\users\dbwls\anaconda3\lib\site-packages (from scikit-learn>=1.3.1->mlxtend) (3.1.0)
Requirement already satisfied: six>=1.5 in c:\users\dbwls\anaconda3\lib\site-packages (from python-dateutil>=2.7->matplotlib>=3.0.0->mlxtend) (1.16.0)

In [66]:
import pandas as pd
from mlxtend.preprocessing import TransactionEncoder
from mlxtend.frequent_patterns import apriori, association_rules

In [68]:
# 리스트의 리스트 형태로 트랜잭션 구성
dataset = [['빵', '우유', '씨리얼'],
           ['빵', '기저귀', '맥주', '계란'],
           ['우유', '기저귀', '맥주', '콜라'],
           ['빵', '우유', '기저귀', '맥주'],
           ['빵', '우유', '기저귀', '콜라', '삼겹살'],
           ['우유', '계란', '씨리얼'],
           ['우유', '기저귀', '콜라', '맥주'],
           ['삼겹살', '콜라', '맥주'],
           ['빵', '우유', '기저귀', '맥주', '계란',],
           ['우유', '빵'],
           ['우유', '씨리얼']]

In [70]:
# TransactionEncoder는 리스트의 리스트로 구성된 트랜잭션 데이터를 NumPy 배열로 인코딩하기 위함

te = TransactionEncoder()
te_ary = te.fit(dataset).transform(dataset)
te_ary

array([[False, False, False,  True, False,  True,  True, False],
       [ True,  True,  True,  True, False, False, False, False],
       [False,  True,  True, False, False, False,  True,  True],
       [False,  True,  True,  True, False, False,  True, False],
       [False,  True, False,  True,  True, False,  True,  True],
       [ True, False, False, False, False,  True,  True, False],
       [False,  True,  True, False, False, False,  True,  True],
       [False, False,  True, False,  True, False, False,  True],
       [ True,  True,  True,  True, False, False,  True, False],
       [False, False, False,  True, False, False,  True, False],
       [False, False, False, False, False,  True,  True, False]])

In [72]:
te.columns_

['계란', '기저귀', '맥주', '빵', '삼겹살', '씨리얼', '우유', '콜라']

In [74]:
df = pd.DataFrame(te_ary, columns=te.columns_)
df

       계란    기저귀     맥주      빵    삼겹살    씨리얼     우유     콜라
0   False  False  False   True  False   True   True  False
1    True   True   True   True  False  False  False  False
2   False   True   True  False  False  False   True   True
3   False   True   True   True  False  False   True  False
4   False   True  False   True   True  False   True   True
5    True  False  False  False  False   True   True  False
6   False   True   True  False  False  False   True   True
7   False  False   True  False   True  False  False   True
8    True   True   True   True  False  False   True  False
9   False  False  False   True  False  False   True  False
10  False  False  False  False  False   True   True  False

In [76]:
# 지지도 확인
frequent_itemsets = apriori(df, min_support = 0.3, use_colnames = True)
frequent_itemsets

     support       itemsets
0   0.545455          (기저귀)
1   0.545455           (맥주)
2   0.545455            (빵)
3   0.818182           (우유)
4   0.363636           (콜라)
5   0.454545      (기저귀, 맥주)
6   0.363636       (빵, 기저귀)
7   0.454545      (기저귀, 우유)
8   0.363636       (우유, 맥주)
9   0.454545        (빵, 우유)
10  0.363636  (우유, 기저귀, 맥주)

In [80]:
# 신뢰도 확인
association_rules(frequent_itemsets, metric="confidence", min_threshold=0.3, num_itemsets = 0)

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
0,(기저귀),(맥주),0.545455,0.545455,0.454545,0.833333,1.527778,1.0,0.157025,2.727273,0.760000,0.714286,0.633333,0.833333
1,(맥주),(기저귀),0.545455,0.545455,0.454545,0.833333,1.527778,1.0,0.157025,2.727273,0.760000,0.714286,0.633333,0.833333
2,(빵),(기저귀),0.545455,0.545455,0.363636,0.666667,1.222222,1.0,0.066116,1.363636,0.400000,0.500000,0.266667,0.666667
3,(기저귀),(빵),0.545455,0.545455,0.363636,0.666667,1.222222,1.0,0.066116,1.363636,0.400000,0.500000,0.266667,0.666667
4,(기저귀),(우유),0.545455,0.818182,0.454545,0.833333,1.018519,1.0,0.008264,1.090909,0.040000,0.500000,0.083333,0.694444
5,(우유),(기저귀),0.818182,0.545455,0.454545,0.555556,1.018519,1.0,0.008264,1.022727,0.100000,0.500000,0.022222,0.694444
6,(우유),(맥주),0.818182,0.545455,0.363636,0.444444,0.814815,1.0,-0.082645,0.818182,-0.555556,0.363636,-0.222222,0.555556
7,(맥주),(우유),0.545455,0.818182,0.363636,0.666667,0.814815,1.0,-0.082645,0.545455,-0.333333,0.363636,-0.833333,0.555556
8,(빵),(우유),0.545455,0.818182,0.454545,0.833333,1.018519,1.0,0.008264,1.090909,0.040000,0.500000,0.083333,0.694444
9,(우유),(빵),0.818182,0.545455,0.454545,0.555556,1.018519,1.0,0.008264,1.022727,0.100000,0.500000,0.022222,0.694444
10,"(기저귀, 우유)",(맥주),0.454545,0.545455,0.363636,0.800000,1.466667,1.0,0.115702,2.272727,0.583333,0.571429,0.560000,0.733333
11,"(맥주, 우유)",(기저귀),0.363636,0.545455,0.363636,1.000000,1.833333,1.0,0.165289,inf,0.714286,0.666667,1.000000,0.833333
12,"(기저귀, 맥주)",(우유),0.454545,0.818182,0.363636,0.800000,0.977778,1.0,-0.008264,0.909091,-0.040000,0.400000,-0.100000,0.622222
13,(우유),"(기저귀, 맥주)",0.818182,0.454545,0.363636,0.444444,0.977778,1.0,-0.008264,0.981818,-0.111111,0.400000,-0.018519,0.622222
14,(기저귀),"(맥주, 우유)",0.545455,0.363636,0.363636,0.666667,1.833333,1.0,0.165289,1.909091,1.000000,0.666667,0.476190,0.833333
15,(맥주),"(기저귀, 우유)",0.545455,0.454545,0.363636,0.666667,1.466667,1.0,0.115702,1.636364,0.700000,0.571429,0.388889,0.733333

In [84]:
# 향상도 확인
association_rules(frequent_itemsets, metric="lift", min_threshold=1, num_itemsets = 0)

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
0,(기저귀),(맥주),0.545455,0.545455,0.454545,0.833333,1.527778,1.0,0.157025,2.727273,0.760000,0.714286,0.633333,0.833333
1,(맥주),(기저귀),0.545455,0.545455,0.454545,0.833333,1.527778,1.0,0.157025,2.727273,0.760000,0.714286,0.633333,0.833333
2,(빵),(기저귀),0.545455,0.545455,0.363636,0.666667,1.222222,1.0,0.066116,1.363636,0.400000,0.500000,0.266667,0.666667
3,(기저귀),(빵),0.545455,0.545455,0.363636,0.666667,1.222222,1.0,0.066116,1.363636,0.400000,0.500000,0.266667,0.666667
4,(기저귀),(우유),0.545455,0.818182,0.454545,0.833333,1.018519,1.0,0.008264,1.090909,0.040000,0.500000,0.083333,0.694444
5,(우유),(기저귀),0.818182,0.545455,0.454545,0.555556,1.018519,1.0,0.008264,1.022727,0.100000,0.500000,0.022222,0.694444
6,(빵),(우유),0.545455,0.818182,0.454545,0.833333,1.018519,1.0,0.008264,1.090909,0.040000,0.500000,0.083333,0.694444
7,(우유),(빵),0.818182,0.545455,0.454545,0.555556,1.018519,1.0,0.008264,1.022727,0.100000,0.500000,0.022222,0.694444
8,"(기저귀, 우유)",(맥주),0.454545,0.545455,0.363636,0.800000,1.466667,1.0,0.115702,2.272727,0.583333,0.571429,0.560000,0.733333
9,"(맥주, 우유)",(기저귀),0.363636,0.545455,0.363636,1.000000,1.833333,1.0,0.165289,inf,0.714286,0.666667,1.000000,0.833333
10,(기저귀),"(맥주, 우유)",0.545455,0.363636,0.363636,0.666667,1.833333,1.0,0.165289,1.909091,1.000000,0.666667,0.476190,0.833333
11,(맥주),"(기저귀, 우유)",0.545455,0.454545,0.363636,0.666667,1.466667,1.0,0.115702,1.636364,0.700000,0.571429,0.388889,0.733333

In [88]:
df_assoc = association_rules(frequent_itemsets, metric="lift", min_threshold=1.2, num_itemsets = 0
                        )
df_assoc.sort_values('lift', ascending=False) #lift 기준 내림차순 정렬

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
5,"(맥주, 우유)",(기저귀),0.363636,0.545455,0.363636,1.000000,1.833333,1.0,0.165289,inf,0.714286,0.666667,1.000000,0.833333
6,(기저귀),"(맥주, 우유)",0.545455,0.363636,0.363636,0.666667,1.833333,1.0,0.165289,1.909091,1.000000,0.666667,0.476190,0.833333
0,(기저귀),(맥주),0.545455,0.545455,0.454545,0.833333,1.527778,1.0,0.157025,2.727273,0.760000,0.714286,0.633333,0.833333
1,(맥주),(기저귀),0.545455,0.545455,0.454545,0.833333,1.527778,1.0,0.157025,2.727273,0.760000,0.714286,0.633333,0.833333
4,"(기저귀, 우유)",(맥주),0.454545,0.545455,0.363636,0.800000,1.466667,1.0,0.115702,2.272727,0.583333,0.571429,0.560000,0.733333
7,(맥주),"(기저귀, 우유)",0.545455,0.454545,0.363636,0.666667,1.466667,1.0,0.115702,1.636364,0.700000,0.571429,0.388889,0.733333
2,(빵),(기저귀),0.545455,0.545455,0.363636,0.666667,1.222222,1.0,0.066116,1.363636,0.400000,0.500000,0.266667,0.666667
3,(기저귀),(빵),0.545455,0.545455,0.363636,0.666667,1.222222,1.0,0.066116,1.363636,0.400000,0.500000,0.266667,0.666667